# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/SOC_Final_Project_Snake_Game/SnakeGame/SnakeGame.srcs/sources_1/bd/SnakeGame_BD/ip/SnakeGame_BD_processing_system7_0_0/SnakeGame_BD_processing_system7_0_0.xci
# IP: The module: 'SnakeGame_BD_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/SOC_Final_Project_Snake_Game/SnakeGame/SnakeGame.srcs/sources_1/bd/SnakeGame_BD/ip/SnakeGame_BD_processing_system7_0_0/SnakeGame_BD_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'SnakeGame_BD_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/SOC_Final_Project_Snake_Game/SnakeGame/SnakeGame.srcs/sources_1/bd/SnakeGame_BD/ip/SnakeGame_BD_processing_system7_0_0/SnakeGame_BD_processing_system7_0_0.xci
# IP: The module: 'SnakeGame_BD_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/SOC_Final_Project_Snake_Game/SnakeGame/SnakeGame.srcs/sources_1/bd/SnakeGame_BD/ip/SnakeGame_BD_processing_system7_0_0/SnakeGame_BD_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'SnakeGame_BD_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
