# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/SnakeGame_BD/SnakeGame_BD.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SnakeGame_BD || ORIG_REF_NAME==SnakeGame_BD} -quiet] -quiet

# IP: bd/SnakeGame_BD/ip/SnakeGame_BD_processing_system7_0_0/SnakeGame_BD_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SnakeGame_BD_processing_system7_0_0 || ORIG_REF_NAME==SnakeGame_BD_processing_system7_0_0} -quiet] -quiet

# IP: bd/SnakeGame_BD/ip/SnakeGame_BD_axi_gpio_0_0/SnakeGame_BD_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SnakeGame_BD_axi_gpio_0_0 || ORIG_REF_NAME==SnakeGame_BD_axi_gpio_0_0} -quiet] -quiet

# IP: bd/SnakeGame_BD/ip/SnakeGame_BD_axi_gpio_1_0/SnakeGame_BD_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SnakeGame_BD_axi_gpio_1_0 || ORIG_REF_NAME==SnakeGame_BD_axi_gpio_1_0} -quiet] -quiet

# IP: bd/SnakeGame_BD/ip/SnakeGame_BD_ps7_0_axi_periph_0/SnakeGame_BD_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SnakeGame_BD_ps7_0_axi_periph_0 || ORIG_REF_NAME==SnakeGame_BD_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/SnakeGame_BD/ip/SnakeGame_BD_rst_ps7_0_100M_0/SnakeGame_BD_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SnakeGame_BD_rst_ps7_0_100M_0 || ORIG_REF_NAME==SnakeGame_BD_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/SnakeGame_BD/ip/SnakeGame_BD_xbar_0/SnakeGame_BD_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SnakeGame_BD_xbar_0 || ORIG_REF_NAME==SnakeGame_BD_xbar_0} -quiet] -quiet

# IP: bd/SnakeGame_BD/ip/SnakeGame_BD_auto_pc_0/SnakeGame_BD_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SnakeGame_BD_auto_pc_0 || ORIG_REF_NAME==SnakeGame_BD_auto_pc_0} -quiet] -quiet

# XDC: bd/SnakeGame_BD/SnakeGame_BD_ooc.xdc
